/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/megacamelus/qdrant-operator/api/qdrant/v1alpha1"
	qdrantv1alpha1 "github.com/megacamelus/qdrant-operator/pkg/client/qdrant/applyconfiguration/qdrant/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCollections implements CollectionInterface
type FakeCollections struct {
	Fake *FakeQdrantV1alpha1
	ns   string
}

var collectionsResource = v1alpha1.SchemeGroupVersion.WithResource("collections")

var collectionsKind = v1alpha1.SchemeGroupVersion.WithKind("Collection")

// Get takes name of the collection, and returns the corresponding collection object, and an error if there is any.
func (c *FakeCollections) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Collection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(collectionsResource, c.ns, name), &v1alpha1.Collection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Collection), err
}

// List takes label and field selectors, and returns the list of Collections that match those selectors.
func (c *FakeCollections) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CollectionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(collectionsResource, collectionsKind, c.ns, opts), &v1alpha1.CollectionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CollectionList{ListMeta: obj.(*v1alpha1.CollectionList).ListMeta}
	for _, item := range obj.(*v1alpha1.CollectionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested collections.
func (c *FakeCollections) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(collectionsResource, c.ns, opts))

}

// Create takes the representation of a collection and creates it.  Returns the server's representation of the collection, and an error, if there is any.
func (c *FakeCollections) Create(ctx context.Context, collection *v1alpha1.Collection, opts v1.CreateOptions) (result *v1alpha1.Collection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(collectionsResource, c.ns, collection), &v1alpha1.Collection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Collection), err
}

// Update takes the representation of a collection and updates it. Returns the server's representation of the collection, and an error, if there is any.
func (c *FakeCollections) Update(ctx context.Context, collection *v1alpha1.Collection, opts v1.UpdateOptions) (result *v1alpha1.Collection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(collectionsResource, c.ns, collection), &v1alpha1.Collection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Collection), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCollections) UpdateStatus(ctx context.Context, collection *v1alpha1.Collection, opts v1.UpdateOptions) (*v1alpha1.Collection, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(collectionsResource, "status", c.ns, collection), &v1alpha1.Collection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Collection), err
}

// Delete takes name of the collection and deletes it. Returns an error if one occurs.
func (c *FakeCollections) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(collectionsResource, c.ns, name, opts), &v1alpha1.Collection{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCollections) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(collectionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CollectionList{})
	return err
}

// Patch applies the patch and returns the patched collection.
func (c *FakeCollections) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Collection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(collectionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Collection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Collection), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied collection.
func (c *FakeCollections) Apply(ctx context.Context, collection *qdrantv1alpha1.CollectionApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Collection, err error) {
	if collection == nil {
		return nil, fmt.Errorf("collection provided to Apply must not be nil")
	}
	data, err := json.Marshal(collection)
	if err != nil {
		return nil, err
	}
	name := collection.Name
	if name == nil {
		return nil, fmt.Errorf("collection.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(collectionsResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.Collection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Collection), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeCollections) ApplyStatus(ctx context.Context, collection *qdrantv1alpha1.CollectionApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Collection, err error) {
	if collection == nil {
		return nil, fmt.Errorf("collection provided to Apply must not be nil")
	}
	data, err := json.Marshal(collection)
	if err != nil {
		return nil, err
	}
	name := collection.Name
	if name == nil {
		return nil, fmt.Errorf("collection.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(collectionsResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.Collection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Collection), err
}
