name: Build Main

on:
  push:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
    PROJECTS: ${{ github.workspace }}
    OPERATOR_IMAGE: "quay.io/megacamelus/qdrant-operator"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout - Qdrant Operator"
        uses: actions/checkout@v4
        with:
          path: qdrant-operator   
                 
      - name: "Checkout - Camel Assistant Manifests"
        uses: actions/checkout@v3
        with:
          repository: megacamelus/camel-assistant-manifests
          token: ${{ secrets.GITHUB_TOKEN }}
          path: camel-assistant-manifests

      - name: "Set up Go"
        uses: actions/setup-go@v5
        with:
          go-version-file: 'qdrant-operator/go.mod'
          cache-dependency-path: 'qdrant-operator/go.sum'
          check-latest: true
        
      - name: "Login to Container registry"
        uses: docker/login-action@v3
        with:
          registry: "quay.io"
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: "Build"
        run: |
          cd ${{ env.PROJECTS }}/qdrant-operator   
          make build
          make test
          
      - name: "Build Container image"
        run: |
          cd ${{ env.PROJECTS }}/qdrant-operator   
          make docker-build 
          make docker-push
          
      - name: "Determine Container image name"
        id: "compute-image-name"
        run: |
          cd ${{ env.PROJECTS }}/qdrant-operator   
          make crane

          IMAGE_DIGEST=$(./bin/crane digest ${OPERATOR_IMAGE}:latest)
          IMAGE_NAME="${OPERATOR_IMAGE}@${IMAGE_DIGEST}"

          echo "operator_image=${IMAGE_NAME}" >> "$GITHUB_OUTPUT"

      - name: "Create PR for camel-assistant-manifests"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_NAME:  ${{ steps.compute-image-name.outputs.operator_image }}
          BRANCH_NAME: ci-${{ github.run_id }}
        run: |
          cd ${{ env.PROJECTS }}/camel-assistant-manifests
          
          echo "$OPERATOR_IMAGE"
          echo "$IMAGE_DIGEST"
          echo "$IMAGE_NAME"
          echo "$BRANCH_NAME"

          #cd ${{ env.PROJECTS }}/camel-assistant-manifests

          #tree .

          #git checkout -b "${BRANCH_NAME}
          #git config user.email "megacamelus@megacamelus.github.com"
          #git config user.name "megacamelus"

          #cd etc/kubernetes/manifests/qdrant && kustomize edit set image ${IMAGE_NAME}

          #d ${{ env.PROJECTS }}/camel-assistant-manifests
          #cat etc/kubernetes/manifests/qdrant/kustomization.yaml

          #git commit -m "Update qdrant-operator image" etc/kubernetes/manifests/qdrant/kustomization.yaml
          #git reset --hard
          #git push -u origin ${BRANCH_NAME}

          # GH CLI can't find the branch on remote... needs some time :)
          #sleep 15

          #gh config set prompt disabled

          #gh pr create \
          #  --fill \
          #  --base main \
          #  --title "chore(qdrant): update qdrant-operator image to ${IMAGE_NAME}" \
          #  --body "image: ${IMAGE_NAME}"
